import Head from 'next/head';
import styled from 'styled-components';

import OurValue from '@/Comps/About/Our_value';
import Team from '@/Comps/About/Team';
import CountersSection from '@/Comps/Home/CountersSection';
import SupportBrand from '@/Comps/Home/SupportBrand';
import SecondSection from '@/Comps/Home/secondSection';
import ThirdSection from '@/Comps/Home/thirdSection';
import PageHeader from '@/Comps/Page_Header';
import { LanguageSelector } from '@/utils/context';

const Spacer = styled.div`
  width: 1px;
  height: 100px;
`;

function About() {
  const Title = LanguageSelector('معلومات عنا', 'à propos de nous');

  return (
    <div>
      <Head>
        <title>{Title} | SkyOffice Alger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageHeader Title={Title} />
        <Spacer />
        <SecondSection />
        <ThirdSection />
        <OurValue />
        <CountersSection />
        <Team />
        <SupportBrand />
      </main>
    </div>
  );
}

export default About;
