import Head from 'next/head';
import styled from 'styled-components';

import SendAMessage from '@/Comps/Contact/Form';
import GetInTouch from '@/Comps/Contact/GetInTouch';
import MapSection from '@/Comps/Contact/Map';
import PageHeader from '@/Comps/Page_Header';
import { LanguageSelector } from '@/utils/context';

const Spacer = styled.div`
  width: 1px;
  height: 100px;
`;

function Contact() {
  const Title = LanguageSelector('اتصل بنا', 'Contact us');

  return (
    <div>
      <Head>
        <title>{Title} | SkyOffice Alger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageHeader Title={Title} ImageUrl="/contact_header.webp" />
        <Spacer />
        <SendAMessage />
        <MapSection />
        <Spacer />
        <GetInTouch />
      </main>
    </div>
  );
}

export default Contact;
