import Head from 'next/head';
import styled from 'styled-components';

import CountersSection from '@/Comps/Home/CountersSection';
import Testimonials from '@/Comps/Home/Testimonials';
import WhatWeOffer from '@/Comps/Home/WhatWeOfferSection';
import WhyChooseUs from '@/Comps/Home/WhyChooseUs';
import FourthSection from '@/Comps/Home/fourthSection';
import PageHeader from '@/Comps/Page_Header';
import { LanguageSelector } from '@/utils/context';

const Spacer = styled.div`
  width: 1px;
  height: 100px;
`;

function Services() {
  const Title = LanguageSelector('خدمات', 'Prestations de service');

  return (
    <div>
      <Head>
        <title>{Title} | SkyOffice Alger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageHeader Title={Title} ImageUrl="/services_header.webp" />
        <Spacer />
        <WhatWeOffer />
        <FourthSection />
        <CountersSection />
        <WhyChooseUs />
        <Testimonials />
      </main>
    </div>
  );
}

export default Services;
